name: "[10] Fibonacci LFSR generator"
run-name: "[10] Fibonacci LFSR with ${{inputs.stream_number}} sequences of length ${{inputs.stream_length}} Test Suite run"

on:
  workflow_dispatch:
    inputs:
      stream_length:
        description: >
          Stream length (length of one Sequence) is the length of the individual bit stream(s) to be processed.
          NOTE: During the testing phase, NIST commonly evaluated sequences on the order 10^6; hence, results are based on this assumption.
        required: true
        default: '1000000'
        type: choice
        options: ['1', '10', '1000000']
      stream_number:
        description: >
          Bitstreams (number of Sequences)
          NOTE: For Significance level = 0.001, a sample should have at least 1000 sequences!
          The sample should be on the order of the inverse of the significance level (Î±^-1).
        required: true
        default: '1000'
        type: choice
        options: ['1', '10', '100', '1000']

env:
  TEST_NUM: "10"
  DIR_NAME: "AKalashnikovaFibonacciLFSR"

jobs:
  prepare:
    name: Set parameters
    runs-on: ubuntu-latest
    outputs:
      test_num: ${{ env.TEST_NUM }}
      test_dir: ${{ env.DIR_NAME }}
    steps:
    - name: Echo ENV parameters
      run: echo ${{ github.events.inputs.environment }}

  main:
    name: Run test with the parameters
    uses: ./.github/workflows/reusable_lfsr_generator.yml
    needs: prepare
    with:
      test_num: ${{needs.prepare.outputs.test_num}}
      test_dir: ${{needs.prepare.outputs.test_dir}}
      stream_length: ${{inputs.stream_length}}
      stream_number: ${{inputs.stream_number}}
